APIPARAMS = ('cht', 'chbh', 'chtt', 'chdl', 'chco', 'chd', 'chs', 'chf', 'chts', 'chl', 'chxt', 'chxl', 'chg', 'chxr', 'chxs', 'chls', 'chm', 'chxp')
MARKERS = ('a', 'c', 'd', 'o', 's', 'v', 'V', 'h', 'x', 'r', 'R', 'b', 'B')
TYPES = ('lc', 'lxy', 'bhs', 'bvs', 'bhg', 'bvg', 'p', 'p3', 'v', 's')
IMGATTRS = ('align', 'border', 'height', 'width', 'ismap', 'longdesc', 'usemap', 'id', 'class', 'style', 'lang', 'xml:lang', 'onclick', 'ondblclick', 'onmousedown', 'onmouseup', 'onmouseover', 'onmousemove', 'onmouseout', 'onkeypress', 'onkeydown', 'onkeyup')
TTITLES = ('Line','Line XY','Horizontal bar stack','Vertical bar stack','Horizontal bar group','Vertical bar group','Pie','3D Pie','Venn','Scatter')
